defaults:
  - _self_

hydra:
  run:
    dir: "results/outputs/" 

model:
  name: "NPR"

seed: 42
trainer:
  max_epochs: 30
  optimizer:
    name: "adamW"
    lr: 1e-5 # NPR is 1e-5
    betas: [0.9,0.999]
    weight_decay: 0.1
  loss_fn:
    name: "binary_cross_entropy"
  val_check_interval: 2
  num_gpus: 1
  device_ids: [0,1,2,3]

data:
  feature_type: image
  dataset_name: "GenVideo"
  num_workers: 16
  data_path: "../Data/${data.dataset_name}"
  num_frames: 8
  generation_model: "Pika" 
  input_shape: [224,224]
  train_real_model: "Kinetics-400"
  test_real_model: "MSR-VTT"
  val_real_model: "MSR-VTT"
  train_load_len: 10000
  test_load_len: 500
  batch_size: 24
  val_batch_size: 24

ckpt_path: results/ckpts/baselines/standard-Pika-npr/best_auroc_ckpt.pth
experiment_name: "standard-Pika-npr"
log_path: "./results/test/baselines"
save_csv_file: standard-Pika-npr.csv