checkpoint_path: /data/Umar/Repos/NSG-VD/ckpts/standard-SEINE-d.pth
device: cuda
device_id: 0
diffuse_steps: 5
epsilon: 1.0e-10
feature_dim: 300
feature_type: velocity
img_size: 224
is_smooth: true
is_yy_zero: true
model_name: NSG-VD
num_frames: 8
ref_data_path: reference_standard-SEINE-d/ref_data.pt
ref_features_path: reference_standard-SEINE-d/feature_ref.pt
resolution_size: 224
score_args_path: ./libs/eps_ad/args.yml
score_config_path: ./libs/eps_ad/imagnet.yml
sigma: 1.0
sigma0: 0.1
threshold: 1.0
